name: invsys
channels:
  - anaconda
  - conda-forge
  - defaults
api_keys:
  alpha_vantage: "YOUR_ALPHA_VANTAGE_API_KEY_HERE"
dependencies:
  - appnope=0.1.3
  - asttokens=2.0.5
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.6.4
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openssl=3.0.16
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.8.0
  - pip=25.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python>=3.10,<3.14
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - tzdata=2025a
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  
